"""Full-pipeline regression test.

Runs the complete PlaceCellDataset pipeline on a small data subset and
compares every output against a saved reference bundle.  The reference
was generated by ``generate_regression_data.py`` (one-time, requires
ProcData drive).
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from placecell.dataset import PlaceCellDataset


REGRESSION_DIR = Path(__file__).parent / "assets" / "regression"


@pytest.fixture(scope="module")
def pipeline_result() -> PlaceCellDataset:
    """Run the full pipeline once for all tests in this module."""
    ds = PlaceCellDataset.from_yaml(
        REGRESSION_DIR / "analysis_config.yaml",
        REGRESSION_DIR / "data_paths.yaml",
    )
    ds.load()
    ds.preprocess_behavior()
    ds.deconvolve()
    ds.match_events()
    ds.compute_occupancy()
    ds.analyze_units()
    return ds


@pytest.fixture(scope="module")
def reference() -> PlaceCellDataset:
    """Load the reference bundle."""
    return PlaceCellDataset.load_bundle(REGRESSION_DIR / "reference.pcellbundle")


# ── Summary ──────────────────────────────────────────────────────────


@pytest.mark.timeout(120)
def test_summary_counts(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Pipeline summary counts must match the reference."""
    assert pipeline_result.summary() == reference.summary()


# ── Deconvolution ────────────────────────────────────────────────────


def test_good_unit_ids(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Deconvolved unit IDs must match."""
    assert pipeline_result.good_unit_ids == reference.good_unit_ids


def test_event_index_shape(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Event index row count must match."""
    assert len(pipeline_result.event_index) == len(reference.event_index)


# ── Event–place matching ─────────────────────────────────────────────


def test_event_place_shape(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Matched event count must match."""
    assert len(pipeline_result.event_place) == len(reference.event_place)


# ── Occupancy ────────────────────────────────────────────────────────


def test_occupancy_map(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Occupancy map must match reference."""
    np.testing.assert_allclose(
        pipeline_result.occupancy_time,
        reference.occupancy_time,
        rtol=1e-5,
    )


def test_valid_mask(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Valid mask must match reference."""
    np.testing.assert_array_equal(
        pipeline_result.valid_mask,
        reference.valid_mask,
    )


# ── Per-unit analysis results ────────────────────────────────────────


def test_unit_result_ids(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Analyzed unit IDs must match."""
    assert sorted(pipeline_result.unit_results.keys()) == sorted(
        reference.unit_results.keys()
    )


def test_unit_scalars(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Per-unit scalar metrics (SI, p_val, stability) must match."""
    for uid in reference.unit_results:
        ref = reference.unit_results[uid]
        got = pipeline_result.unit_results[uid]

        assert got.si == pytest.approx(ref.si, rel=1e-5), f"unit {uid} SI"
        assert got.p_val == pytest.approx(ref.p_val, rel=1e-5), f"unit {uid} p_val"
        assert got.stability_corr == pytest.approx(
            ref.stability_corr, nan_ok=True, rel=1e-5
        ), f"unit {uid} stability_corr"
        assert got.stability_z == pytest.approx(
            ref.stability_z, nan_ok=True, rel=1e-5
        ), f"unit {uid} stability_z"
        assert got.stability_p_val == pytest.approx(
            ref.stability_p_val, nan_ok=True, rel=1e-5
        ), f"unit {uid} stability_p_val"


def test_rate_maps(
    pipeline_result: PlaceCellDataset,
    reference: PlaceCellDataset,
) -> None:
    """Per-unit rate maps must match."""
    for uid in reference.unit_results:
        ref_map = reference.unit_results[uid].rate_map
        got_map = pipeline_result.unit_results[uid].rate_map
        assert got_map.shape == ref_map.shape, f"unit {uid} rate_map shape"
        np.testing.assert_allclose(
            got_map,
            ref_map,
            rtol=1e-5,
            equal_nan=True,
            err_msg=f"unit {uid} rate_map",
        )
